### ISSUE TITLE
Questions...

### ISSUE THREAD

**Issue by Draven714** [panique/mini#175]
Question 1: instead of putting all the song methods (getsong(), updatesong()) in model.php how could I separate it and put them into a SongModel.php file which extends the Model class and still automatically load that model?

Question 2: Instead of redirecting to a page after adding a song (header('location: ' . URL . 'songs/index');) I'd like to display a message saying the song was added.
How should I go about that? Adding the views in the addSong() method, commenting out the header()?
Using a $_SESSION that holds the message?
What's the best way using your framework setup?

**Comment by panique** [comment]
I don't know, do this by yourself! This is not your free please-write-my-code board.

Beside, you could do this within 5minutes by simply doing some work and having a look on the code for some seconds.

Please alos don't ask stupid questions like "what's the best way using your framework", this simply makes no sense, and there's no way to answer this. I mean, seriously.
