### ISSUE TITLE
[Question] Is it possible to do this? I can't think of a way.

### ISSUE THREAD

**Issue by razuro** [panique/mini#176]
Hello,

Based on the example demo, imagine if we add a genre detail to the song.

Then can we get all songs based on genre using GET like this: 
http://example.com/mini/songs/rock

and refine the list by appending the singer/band like this:
http://example.com/mini/songs/rock/scorpions

I've modified the index() to index($genre) but it seems index() doesnt like extra parameter.
Warning: Missing argument 1 for Songs::index() eventhough I passed the argument to index.

Sorry for a noob post. Thank you in advance for anwsering my question.

**Comment by Dominic28** [comment]
Yes that's possible, but you would need to change some core stuff.

If you call http://example.com/mini/songs/ the script calls the index method of the songs controller. So you are calling http://example.com/mini/songs/index.

To call this: http://example.com/mini/songs/rock you would need a method named rock in the songs controller.

**Comment by razuro** [comment]
Thank you. I've figured that would require another pre-define method. Can we do that just by calling from database. Get genre from db, then generate that method on the fly? Meaning, it is not necessary to pre-create all existing genres as methods. 

That would be tedious right?

**Comment by panique** [comment]
@all: I'm currently writing a documentation for this, so then problems like this should be much easier to handle :)

**Comment by panique** [comment]
@razuro Typically the index methods are not used with parameters, as they are some kinds of "neutral" entry points to certain parts of the application. As MINI is just supersimply I think it's okay to leave it like it is and use parameters only on all other methods, but keep /xxxx/index always simple and without parameters.

if you really really needs then it should be possible to do this by changing the core in Application.php, but the more simple way would be to work arund this by using another method.

**Comment by razuro** [comment]
Thank you very much @Dominic28 and @panique.
