### ISSUE TITLE
Strip index method when it is present to its controller

### ISSUE THREAD

**Issue by dvLden** [panique/mini#177]
Let's say that controller is for Home and obviously it has a method of index().

If I type:
http://mvc.dev/home/
It will load the actual index method as specified in "core/application"

Then if I type:
http://mvc.dev/home/index
It will load index method again, which is not the behaviour that I'd want. 

How to modify this so that it strips index method if present, because index is always default if no method is present. Any way for this, because I am trying something with .htaccess and I'm failing.

**Comment by panique** [comment]
Sorry I dont understand the problem. home/index will load the index action in home controller, like in every other framework in the world too.

**Comment by dvLden** [comment]
Never used any framework, because I just jumped into MVC pattern and I find that your MVC mini is very clean, straight-forward and easy to understand and learn from.

I will try to clarify things a bit...

I know it is normal that home/index will load index action, so as home without index specified. But I'd like to do something, so that if index as action is defined into url, get rid of it automatically (.htaccess I guess) because it is known that index is default action.

I just wonder what is the way to do it and is it possible to do it? 
Thank you in advance.
