### ISSUE TITLE
URL still rewritting while directory removed

### ISSUE THREAD

**Issue by gvvilsteren** [panique/mini#188]
This evening I removed the 'mini-master' directory from my '/var/www/html/' directory to try out mini2.
But now every link I go to in '/var/www/html' is getting rewritten to 'localhost/mini-master/public'.

Does someone have a solution for this?

edit

Somehow after 1 hour it fixed itself.

**Comment by panique** [comment]
Sorry, but this makes absolutly no sense, and this is definitly not how the install tutorial says how to install. Please always stick to the install tutorials of the according projects, dont mix projects (mini and mini2 are two different things) or use the bulletproof auto-installer.

**Comment by gvvilsteren** [comment]
@Chris this 'thing' happend between the removal of the mini-master directory and the installing of mini2-master. Not while installing mini2-admin.

**Comment by panique** [comment]
Hey, I really dont know what you mean with "mini2-admin", sorry.

**Comment by gvvilsteren** [comment]
Sorry, autocorrect. Meant mini2 or mini2-master as the directory is called.
But it somehow fixed itself yesterday.
