### ISSUE TITLE
Error 403 from the begining 

### ISSUE THREAD

**Issue by khru** [panique/mini#199]
I've just install mini, and it happens that some how when I access 192.168.33.44 apache shows a 403 forbbiden message.

This is my site configuration:

```xml
<VirtualHost *:80>
    DocumentRoot "/var/www/html/myproject/public"
    <Directory "/var/www/html/myproject/public">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
```

The rewrite mod is enabled.

If I disabled the site, I can access to the server but not to the myproject folder.

**Comment by panique** [comment]
Have you used the auto-installer ? and please give some details on your OS etc

**Comment by khru** [comment]
I've used Vagrant 100% autoinstaller

**Comment by khru** [comment]
I've tried to delete myproject an found this as a result:

`default: AH00112: Warning: DocumentRoot [/var/www/html/myproject/public] does not exist
`

**Comment by khru** [comment]
I think I see the problem:

``` bash
drwx------  1 vagrant vagrant 4096 Dec  9 11:04 html
```
``` bash
drwxrwxr-x 1 vagrant vagrant  4096 Dec  9 11:05 myproject
```
I believed that the owner must be www-data

**Comment by khru** [comment]
Becuse i've changed the permissions composer doesn't work...

**Comment by panique** [comment]
Hey, thanks for the feedback!

I think you are right, this was also a problem in another project that used nearly the same auto-installer, and there's I've fixed it by replacing

```
# create project folder
sudo mkdir "/var/www/html/${PROJECTFOLDER}"
```
with
```
# Create project folder, written in 3 single mkdir-statements to make sure this runs everywhere without problems
sudo mkdir "/var/www"
sudo mkdir "/var/www/html"
sudo mkdir "/var/www/html/${PROJECTFOLDER}"
```

I cannot explain exactly why and how this works better, but it does in lots of installation of HUGE (https://github.com/panique/huge/blob/master/_one-click-installation/bootstrap.sh), therefore it should be the same for MINI.

I've changed this now in develop and master branch inside this project here, please gimme some time for testting ! :)
