### ISSUE TITLE
Https problem

### ISSUE THREAD

**Issue by Jakub41** [panique/mini#201]
Hello,

I'm using your framework for a school project and I have an issue with the https request. 
My problem is here: https://46.101.127.220/ 
How you will see the site is messy and I don't know how to fix this. 
One of the requirements of the project is to have SSL and HTTPS requests. 
Can you help me to understand how to fix this?
I don't know if I need to fix something in the HTACCESS or in the code directly. 
Please help me.
Thank you,
Jakub

**Comment by dvLden** [comment]
Check the console @Jakub41... It's a mess because you are loading all of your images, styles and scripts through `http://` and not `https://`.

I am not home, else I would download the `mini` and check out wether it has one https switch option or every request should be manually replaced. That's why I always use `//` instead of hard-coded protocol.

**Comment by panique** [comment]
Hey guys, you can edit this via
```
define('URL_PROTOCOL', 'http://');
```
in the file *application/config/config.php* !

:)

**Comment by Jakub41** [comment]
Il 08/01/16 10:46, Nenad Novakovic ha scritto:
>
> Check the console @Jakub41 <https://github.com/Jakub41>... It's a mess 
> because you are loading all of your images, styles and scripts through 
> |http://| and not |https://|.
>
> I am not home, else I would download the |mini| and check out wether 
> it has one https switch option or every request should be manually 
> replaced. That's why I always use |//| instead of hard-coded protocol.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/panique/mini/issues/201#issuecomment-169949222>.
>
Thanks I was thinking the same I will check and see if I would be able 
to fix it

**Comment by Jakub41** [comment]
Hey I changed to HTTPS in in the file application/config/config.php but get worst. 
Is possible to switch between the 2 because I have to show the project on both protocols?

**Comment by JaoNoctus** [comment]
@Jakub41 try this:

```
define('URL_PROTOCOL', '//');
```

**Comment by Jakub41** [comment]
Thank you I solved the problem :)

**Comment by JaoNoctus** [comment]
:+1:
