### ISSUE TITLE
php-mini.com domain has expired

### ISSUE THREAD

**Issue by lardconcepts** [panique/mini#203]
In https://github.com/panique/mini/blob/develop/public/index.php

     * @link http://www.php-mini.com

But...

"This domain may be for sale. Backorder this Domain"

**Comment by panique** [comment]
Thanks, I know, but some domain-grabber trolls have taken the domain and want a lot of money to give it away. And I really don't want/can pay a lot of money for a simple domain for a free open-source project :)

**Comment by lardconcepts** [comment]
How annoying for you. Never mind - but the php-mini project itself is still alive, yes?

Anyway, I just thought I'd let you know so you could change the code - I didn't want to make a pull request without notifying someone. Thanks again for your good work on this project, and sorry this has happened to you.

**Comment by panique** [comment]
Okay I've now removed the old link in develop andmaster branch! :) Yeah, open source is sometimes really frustrating! The project is definitely still alive, but as it's "finished" somehow there are not really changes, unless somebody finds serious bugs.
