### ISSUE TITLE
[QUESTION] How to use with multiple databases

### ISSUE THREAD

**Issue by exilod** [panique/mini#205]
Hello!
It is possible to implement multiple databases using PDO on mini?

**Comment by panique** [comment]
Sure, but that's totally out of concept of this little script. It's for super-minimal setups, and using two databases is really really advanced.

**Comment by exilod** [comment]
Thanks for the reply. I saw you use only one file for models. It is possible to rewrite the structure to use multiple model files?

**Comment by panique** [comment]
Sure it's possible, just do it!
