### ISSUE TITLE
How to redirct to another view?

### ISSUE THREAD

**Issue by rsmmukesh** [panique/mini#206]
How to redirct to another view?
for example when Logout i need to call logout action... from the logout i need to redirect to login page.
please give me the solution

**Comment by panique** [comment]
this has nothing to do with MINI, have a look on redirects with PHP

**Comment by kimminahm** [comment]
$.$ ,  .pllm [
.9.m99.j9.9

**Comment by rsmmukesh** [comment]
ok thank you
