### ISSUE TITLE
Serving http and https issues

### ISSUE THREAD

**Issue by ynohtna92** [panique/mini#208]
In the config.php file `define('URL_PROTOCOL', 'http://');` should be `define('URL_PROTOCOL', '//');` instead to allow for https protocol definitions when using URL.

**Comment by panique** [comment]
Hi, totally agree, but at time of writing i thought people who use this are mostly beginners so they will not work with https and stuff. Gimme some time to implement and test please!

**Comment by panique** [comment]
fixed with https://github.com/panique/mini/commit/e7bb76ff69dc91e77b76bec3b2a65be1d33364e8
