### ISSUE TITLE
[in TODO] PHP 7 Cannot declare class Error

### ISSUE THREAD

**Issue by codebicycle** [panique/mini#209]
>"Fatal error: Cannot declare class Error, because the name is already in use ..."

Error is a class used internally by PHP 7, it is the base class for all internal PHP errors.
[link to manual](https://secure.php.net/manual/en/class.error.php)

Solution: rename class Error from error controller to something else.
Fallowing references to error should be modified.
- in controller/error.php
  - filename
 - `* Class Error` comment
  - `class Error extends Controller`
  - `require APP . 'view/error/index.php';`
- view/error folder
- in core/application.php
  - 2x `header('location: ' . URL . 'error');`

**Comment by cuplizian** [comment]
Why didn't just create pull request?

**Comment by codebicycle** [comment]
>"There are only two hard problems in Computer Science:
   cache invalidation and naming things." - Phil Karlton

**Comment by panique** [comment]
Thank for the find in the good infi, I'll have a look when there's some free time and provide a fix!

**Comment by panique** [comment]
thanks, it's fixed in develop branch!
