### ISSUE TITLE
header and footer in 1 file?

### ISSUE THREAD

**Issue by Silvester20** [panique/mini#211]
First of all thanks for this well documented ans easy framework!

Is it possible to have the header.php and footer.php in the folder "views" combined into 1 file, like template.php?

**Comment by ugurozturk** [comment]
May i ask why do you need that ? Even i am using meta.php - header.php - footer.php

**Comment by Silvester20** [comment]
I think this is better; it avoid 1 file request to server and it is easier for me to read the complete layout in that way. Do you know if this easy to achieve?

**Comment by ugurozturk** [comment]
I got what you meaning. Like Asp.NET Master Page. I think you can't do that with that. You must rewrite routings, Application settings. There is no easy way to do that
