### ISSUE TITLE
Problem with case sensitive controller names

### ISSUE THREAD

**Issue by rsmmukesh** [panique/mini#212]
consider the situation controller name is "ErrorController" and it has an action "index". from the localmachine there is no problem, working for the url "localhost\phpminisolution\Error" and "localhost\phpminisolution\error" , then i hosted it in a linux machine , it is not working for "localhost\phpminisolution\error".  i found the problem it fails in the situation "elseif (file_exists(APP . 'controller/' . $this->url_controller . '.php')) " in application.php . can you suggest me a solution as soon as possible?

**Comment by vian** [comment]
Use lowercased controller filenames: 'error.php', 'articles.php', and change the line in question to "else if (file_exists(APP . 'controller/' . mb_strtolower($this->url_controller' . '.php')) "
