### ISSUE TITLE
How to allow a file to access?

### ISSUE THREAD

**Issue by rsmmukesh** [panique/mini#222]
for example i need to allow my sitemap to access " www.sitename.com/sitemap.xml ".
currently it will check for controller and action and it fails. how i can manage it?

**Comment by panique** [comment]
put the file inside the /public folder :)

**Comment by rsmmukesh** [comment]
then how to access the file? "http://localhost/mvc2/public/sitemap.xml" is the link is correct? it is not working

**Comment by rsmmukesh** [comment]
Yes. thank you. i got it.
