### ISSUE TITLE
 Why do I often receive the project's email ?!  Can i close the notifications？

### ISSUE THREAD

**Issue by kmdjs** [panique/mini#230]
many thanks~~

Dingo Star <notifications@github.com>    
(由 bounces+848413-22eb-1653705370=qq.com@sgmail.github.com 代发) 

时   间：2017年1月29日(星期天) 下午3:28 (UTC-08:00 温哥华、洛杉玑、西雅图时间)	
收件人：
panique/mini <mini@noreply.github.com>
抄   送：
Subscribed <subscribed@noreply.github.com>

**Comment by panique** [comment]
I don't know, this project is not changed for years and i definitly don't send out any emails to you, as this is not possible. Maybe you have subscribed for something somewhere ? Maybe look at the WATCH button or so
