### ISSUE TITLE
how to use session??

### ISSUE THREAD

**Issue by ikwijaya** [panique/mini#231]
Dear panique team,

can you produce mini with session or cookies for login access?
[my history]
iam create other model for user login use class User, then create controller (login) with different header and footer, and redirect first url from index (home) to index (login), working fine for authetication User login. But if i use session_start() within page header login and header home, the authentication User login cannot redirect to home page.
Please help me, thanks for your advise. Sorry for my bad english.
Sincerely yours,
ikwijaya

**Comment by borzaka** [comment]
I had problems too when using `session_start();` in `\application\view\_templates\_header.php`.
So I ended up putting `session_start();` into `public/index.php`

**Comment by ikwijaya** [comment]
sorry i was move to python :+1:
