### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by JosephDeFacto** [panique/mini#250]
Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

How to fix this? I am using xammp

**Comment by panique** [comment]
Hi, "additionally" to what ? :) this is your first post here so I'm a little bit clueless.

Can you please describe what exactly you are doing, and what is not working, what software / version you are using etc ? What DOES work ?

**Comment by JosephDeFacto** [comment]
Solved!
